package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "uart",
    srcs = [
        "src/uart.c",
    ],
    hdrs = [
        "inc/uart.h",
    ],
    includes = [
        "inc",
    ]
)
